steps:
  - id: "Static Filesystem Analysis"
    name: "aquasec/trivy:latest"
    args: ["fs","/workspace"]

  - id: "Static Config Analysis"
    name: "aquasec/trivy:latest"
    args: ["config","/workspace"]
    
  - id: "Docker Image scanning"
    name: "aquasec/trivy:latest"
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        trivy image --exit-code 1 --no-progress --severity CRITICAL gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_IMAGE_TAG}

substitutions:
    _IMAGE_NAME: example-nodejs
    _IMAGE_TAG: latest